### ISSUE TITLE
Add validation in Entity Coin

### ISSUE THREAD

**Issue by badrussell** [badrussell/vendor-machine#1]

**Comment by GeradeDev** [comment]
I can do this.

Expect PR next week at the earliest.

**Comment by robertbarclayy** [comment]
Can I please give this a go.

**Comment by badrussell** [comment]
Create a validation 
ex: Coin x = new Coin("XXX");
create error custom

ex: Coin x = new Coin("10");
create error custom

VALID_ENTRY => 0.01 0.05 0.10 0.25 0.50 1.00

GO!

**Comment by sarphiv** [comment]
I created a pull request (#4) with *hopefully* the requested changes.
